### PR TITLE
Convert documentation to markdown 

### PR DESCRIPTION
**Pull request by imobach**
Convert documentation to markdown. BTW add information about openSUSE development.

### CODE REVIEW

**Comment by mvidner** [comment]
Thanks! I wondered what this is useful for, so please add this to the top:
```
libx86emu is a dependency for [hwinfo](https://github.com/openSUSE/hwinfo).
```

**Comment by imobach** [comment]
@mvidner Done. Thanks!

**Comment by mvidner** [comment]
LGTM

**Comment by imobach** [comment]
@mvidner Thanks.

**Pull request merged**
